name: Update Live Channels
on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  update-links:
    runs-with: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Fetch and Save Data
        run: |
          php api/fetcher.php > live_data.json
          cat live_data.json # Debug karne ke liye check karein

      - name: Push Updates
        run: |
          git config --global user.name "Sanskar-Bot"
          git config --global user.email "bot@sanskar.com"
          git add live_data.json
          git commit -m "Auto Update: $(date)" || exit 0
          git push
          
